# run.py - Main Orchestration Script
from agents.planner_agent import PlannerAgent
from agents.data_agent import DataAgent
from agents.insight_agent import InsightAgent
from agents.evaluator_agent import EvaluatorAgent
from agents.creative_agent import CreativeAgent
import json
import os
from datetime import datetime

def generate_insights_json(query, total_campaigns, date_range, avg_roas, avg_ctr):
    insights_data = {
        "analysis_query": query,
        "timestamp": datetime.now().isoformat(),
        "summary_metrics": {
            "total_campaigns": total_campaigns,
            "date_range": date_range,
            "average_roas": round(avg_roas, 2),
            "average_ctr": round(avg_ctr, 2)
        }
    }
    
    with open('insights.json', 'w') as f:
        json.dump(insights_data, f, indent=2)
    print("   ✅ insights.json generated!")

def generate_creatives_json(creative_data):
    with open('creatives.json', 'w') as f:
        json.dump(creative_data, f, indent=2)
    print("   ✅ creatives.json generated!")

def generate_report_md(total_campaigns, date_range, avg_roas, avg_ctr, top_3, bottom_3):
    report_content = f"""# Facebook Ads Performance Analysis Report

## Executive Summary
Multi-agent system analyzed {total_campaigns} campaigns from {date_range}.

## Performance Overview
- **Total Campaigns Analyzed**: {total_campaigns}
- **Date Range**: {date_range}
- **Average ROAS**: {avg_roas:.2f}
- **Average CTR**: {avg_ctr:.2f}%

## Top Performing Campaigns
"""
    if top_3 is not None:
        for campaign, data in top_3.iterrows():
            report_content += f"- **{campaign}**: ROAS={data['roas']}, Spend=${data['spend']}\\n"

    report_content += """
## Recommendations
- Allocate more budget to top performers
- Optimize creatives for low-ROAS campaigns
- Conduct A/B testing for better engagement

---
*Generated by Multi-Agent Analysis System*
"""
    
    with open('report.md', 'w', encoding='utf-8') as f:
        f.write(report_content)
    print("   ✅ report.md generated!")

def main():
    print("🚀 Facebook Ads Analysis System Starting...")
    print("=" * 50)
    
    # Create logs directory
    if not os.path.exists('logs'):
        os.makedirs('logs')
    
    # Initialize all agents
    planner = PlannerAgent()
    data_agent = DataAgent()
    insight_agent = InsightAgent()
    evaluator = EvaluatorAgent()
    creative_agent = CreativeAgent()
    
    user_query = "Analyze ROAS drop"
    print(f"User Query: {user_query}")
    
    # Agentic workflow
    tasks = planner.plan(user_query)
    
    df, total_campaigns, date_range, avg_roas, avg_ctr = data_agent.load_and_analyze_data(
        'synthetic_fb_ads_undergarments.csv'
    )
    
    campaign_stats, top_3, bottom_3 = insight_agent.analyze_campaign_performance(df)
    
    validation_result = evaluator.validate_insights(top_3, bottom_3)
    
    creative_recommendations = creative_agent.generate_recommendations(bottom_3)
    
    # Generate all files
    print("\n📁 Generating output files...")
    generate_insights_json(user_query, total_campaigns, date_range, avg_roas, avg_ctr)
    generate_creatives_json(creative_recommendations)
    generate_report_md(total_campaigns, date_range, avg_roas, avg_ctr, top_3, bottom_3)
    
    # Save log
    log_entry = {
        "timestamp": datetime.now().isoformat(),
        "query": user_query,
        "agents_used": ["Planner", "Data", "Insight", "Evaluator", "Creative"],
        "status": "completed"
    }
    
    with open('logs/analysis_log.json', 'w') as f:
        json.dump(log_entry, f, indent=2)
    
    print("\n" + "=" * 50)
    print("✅ MULTI-AGENT ANALYSIS COMPLETE!")
    print("🤖 5 Agents Executed Successfully")
    print("📁 All Files Auto-Generated")

if __name__ == "__main__":
    main()